name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Authenticate with Firebase
      - name: Firebase Auth
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: use --add
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # 5. Deploy Hosting
      - name: Deploy Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"

      # 6. Deploy Firestore & Storage Rules
      - name: Deploy Rules
        run: firebase deploy --only firestore:rules,storage:rules --token "${{ secrets.FIREBASE_TOKEN }}"

      # 7. Deploy Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
